export const TODO_ACTION_CONST = {
  CREATE_TODO: 'CREATE_TODO',
  SEND_EACH_TODO_ID: 'SEND_EACH_TODO_ID',
  SEND_ALL_TODO_ID: 'SEND_ALL_TODO_ID',
  SELECT_MARK_AS_DONE: 'SELECT_MARK_AS_DONE',
  SELECT_MARK_AS_NOT_DONE: 'SELECT_MARK_AS_NOT_DONE',
  SELECT_DELETE: 'SELECT_DELETE',
};
